server:
  port: 8081

spring:
  profiles:
    active: development
  application:
    title: gateway
    version: 1.0
    name: gateway

  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
  main:
    allow-bean-definition-overriding: true
    web-application-type: reactive
logging:
  level:
    org:
      springframework:
        security: DEBUG
---
spring:
  config:
    activate:
      on-profile: production
  cloud:
    gateway:
      routes:
        - id: auth
          uri: http://auth:8082
          predicates:
            - Path=/api/auth/**
          filters:
            - RewritePath=/api/auth/(?<segment>.*), /$\{segment}
        - id: messages
          uri: http://messages:8080
          predicates:
            - Path=/api/messages/**
          filters:
            - RewritePath=/api/messages/(?<segment>.*), /$\{segment}
        - id: trading
          uri: http://messages:8083
          predicates:
            - Path=/api/trading/**
          filters:
            - RewritePath=/api/trading/(?<segment>.*), /$\{segment}
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
---
spring:
  config:
    activate:
      on-profile: development
  cloud:
    gateway:
      routes:
        - id: auth
          uri: http://auth:8082
          predicates:
            - Path=/api/auth/**
          filters:
            - RewritePath=/api/auth/(?<segment>.*), /$\{segment}
        - id: messages
          uri: http://messages:8080
          predicates:
            - Path=/api/messages/**
          filters:
            - RewritePath=/api/messages/(?<segment>.*), /$\{segment}
        - id: trading
          uri: http://messages:8083
          predicates:
            - Path=/api/trading/**
          filters:
            - RewritePath=/api/trading/(?<segment>.*), /$\{segment}
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"

---
spring:
  config:
    activate:
      on-profile: kubernetes
  cloud:
    gateway:
      routes:
        - id: auth
          uri: http://auth:8082
          predicates:
            - Path=/api/auth/**
          filters:
            - RewritePath=/api/auth/(?<segment>.*), /$\{segment}
        - id: messages
          uri: http://messages:8080
          predicates:
            - Path=/api/messages/**
          filters:
            - RewritePath=/api/messages/(?<segment>.*), /$\{segment}
        - id: trading
          uri: http://messages:8083
          predicates:
            - Path=/api/trading/**
          filters:
            - RewritePath=/api/trading/(?<segment>.*), /$\{segment}
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"